### ISSUE TITLE
Заменить шаги в разделе "Добавить точку с птицей"

### ISSUE THREAD

**Issue by houstonheat** [nextgis/seagull#12]
Сейчас там используется текст из "загрязнения", но он не корректен для животных. 

### Комментарий:
Предлагаю заменить 
![image](https://github.com/user-attachments/assets/d5b234bb-7501-47b8-a576-158e1e5c5aa0)

На:
```
- "Народное" название пляжа или локации (если известно)
- Примерное количество особей
- Видовая принадлежность (если можно определить. Помогает спланировать транспортировку)
4. Есть ли техника
5. Какая требуется помощь (если известно)
```

### Дополнительные кнопки и атрибуты
После координат и комментариев ввести доп. кнопки

Оперение загрязнено: в идеале `enum(да, нет, неизвестно)`, чтобы не было человеческой ошибки

**Comment by houstonheat** [comment]
Отдельно подумаем сейчас над живые/мертвые

Или сюда атрибут, или отдельный слой (потому что  умерших животных надо увозить любого типа и не только птиц. Мб не дублировать)

**Comment by belov-igor** [comment]
> Оперение загрязнено: в идеале enum(да, нет, неизвестно), чтобы не было человеческой ошибки
@houstonheat  вы хотите в таблице, чтоб в итоге был int 1, 2, 3? В смысле ошибиться может потом кто-то?

**Comment by belov-igor** [comment]
Остальное, в принципе, добавлено
![image](https://github.com/user-attachments/assets/526a77e7-2c0b-45ae-ab11-dc0781b9e64f)
![image](https://github.com/user-attachments/assets/3ddc09ab-97d4-4d7d-8d64-678845374177)

по оперению пишет инты 1, 2, 3, исходя из этого порядка 

> enum(да, нет, неизвестно)

**Comment by belov-igor** [comment]
такое же описание используется в комментарии для добавления на слой с мертвыми животными
