### ISSUE TITLE
Кнопка построить маршрут на точку в Яндекс.картах

### ISSUE THREAD

**Issue by simgislab** [nextgis/seagull#13]
По кнопке открывается приложение с автоматически построенным маршрутом от текущего местоположения на точку с координатами.

Кнопку можно в окно идентификации, рядом с копировать ссылку.

Формирование ссылки
https://yandex.ru/dev/yandex-apps-launch-maps/doc/ru/?from=SO

Параметры ссылки
https://yandex.ru/dev/yandex-apps-launch-maps/doc/ru/concepts/yandexmaps-web

**Comment by simgislab** [comment]
в урле как-то тухло, нужно передавать две точки (от-до) епонятно можно ли без ОТ

![20241228_164947](https://github.com/user-attachments/assets/e7d27bfe-2b39-498d-8464-5443aa2720db)

**Comment by simgislab** [comment]
есть такое, когда-то работало: https://www.youtube.com/watch?v=uFGNUIOTbJU

**Comment by Gis-centr** [comment]
У

> есть такое, когда-то работало: https://www.youtube.com/watch?v=uFGNUIOTbJU

сейчас не работает,

открывается на точку такая ссылка:
https://yandex.ru/maps/?&mode=whatshere&whatshere%5Bpoint%5D=37.271361%2C44.971951&whatshere%5Bzoom%5D=11&z=11

**Comment by simgislab** [comment]
формируем ссылки вида
http://maps.yandex.ru/?rtext=~55.76009,37.648801&rtt=auto

должно работать, открывать яндекс.карты с маршрутом от текущего местоположения до точки с координатами

**Comment by simgislab** [comment]
https://t.me/c/2359168750/1/556
