### ISSUE TITLE
Ручной ввод альтернативной даты и времени

### ISSUE THREAD

**Issue by simgislab** [nextgis/seagull#7]
также как ввод координат по маске

**Comment by simgislab** [comment]
+ кнопка Без даты

**Comment by belov-igor** [comment]
ввод даты/времени по маске сделан, формат 24.12.2024 13:51, но может простить случайные запятые или тире вместо точек. Если время вводить будет некогда, можно будет нажать кнопку "Без даты"
![image](https://github.com/user-attachments/assets/9e344f57-7868-4bc8-a3cc-a473cbd9d33a)
