### ISSUE TITLE
Отображать время МСК на карте

### ISSUE THREAD

**Issue by houstonheat** [nextgis/seagull#8]
Время в БД и при передаче клиентом (бот) проставляется по-умолчанию в UTC. Подавляющее большинство внесений будет в часовом поясе MSK (+3) и вряд ли мы будет отмечать в ближайшую неделю точки в других старнах/часовых поясах. 

Нас волнует именно достоверность наблюдений и для большинства принимающих решение важно оперативное время на месте в Анапе и окрестностях, нежели собственная локаль.
![image](https://github.com/user-attachments/assets/42e1ee79-581e-4f4b-ac48-6549be04545a)

**Comment by Gis-centr** [comment]
Исправлено
